###############################################################################
# (c) Copyright 2025 CERN for the benefit of the LHCb Collaboration           #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################

# This is the CI/CD pipeline for the repository mirror in Gitlab.

stages:
  - pre-commit
  - initialisation
  - build
  - test

variables:
  NO_LBLOGIN: "1"
  GIT_SUBMODULE_STRATEGY: none
  GAMMACOMBO_BRANCH: lhcb-paper-2026

check-formatting:
  stage: pre-commit
  image: gitlab-registry.cern.ch/lhcb-docker/os-base/alma9-devel:latest
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - |
      python3 -m venv ${CI_PROJECT_DIR}/.cache/pre-commit-venv
      source ${CI_PROJECT_DIR}/.cache/pre-commit-venv/bin/activate
      pip install --upgrade pip
      pip install -U pre-commit
      pip install six
  script:
    - pre-commit run --all-files --show-diff-on-failure

gammacombo-init:
  stage: initialisation
  tags:
    - cvmfs
  image: gitlab-registry.cern.ch/lhcb-docker/os-base/alma9-devel:latest
  script:
    - |
      echo "Initialise gammacombo repository..."
      git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch/gammacombo/gammacombo.git
      cd gammacombo
      git fetch origin
      echo "Checking out branch ${GAMMACOMBO_BRANCH}..."
      git checkout $GAMMACOMBO_BRANCH
      git pull origin $GAMMACOMBO_BRANCH
      cd ..
      source scripts/setup-env-cvmfs.sh -c || exit 1
  artifacts:
    when: on_success
    untracked: true
    paths:
      - gammacombo
    access: all
    expire_in: 1 days

build_gcc:
  tags:
    - cvmfs
  image: gitlab-registry.cern.ch/lhcb-docker/os-base/alma9-devel:latest
  before_script:
    - source scripts/setup-env-cvmfs.sh || exit 1
  stage: build
  dependencies:
    - gammacombo-init
  script:
    - |
      cmake -B build
      cmake --build build
      cmake --install build

.select_runner:
  tags:
    - cvmfs
  image: gitlab-registry.cern.ch/lhcb-docker/os-base/alma9-devel:latest
  before_script:
    - source scripts/setup-env-cvmfs.sh -c || exit 1

build_clang:
  extends: .select_runner
  stage: build
  dependencies:
    - gammacombo-init
  script:
    - |
      cmake -B build
      cmake --build build
      cmake --install build
  artifacts:
    when: on_success
    untracked: true
    paths:
      - build
      - tutorial
      - gammacombo
    access: all
    expire_in: 1 days

.test:
  extends: .select_runner
  stage: test
  dependencies:
    - build_clang

test-tutorial:
  extends: .test
  stage: test
  script:
    - python scripts/run_ci_tests.py
  artifacts:
    when: always
    paths:
      - tutorial/ci_logs
      - tutorial/plots
      - tutorial/root
      - tutorial/workspace.root
    expire_in: 1 days

test-gammacombo:
  extends: .test
  stage: test
  dependencies:
    - build_clang
  tags:
    - cvmfs
  image: gitlab-registry.cern.ch/lhcb-docker/os-base/alma9-devel:latest
  before_script:
    - |
      source scripts/setup-env-cvmfs.sh -c || exit 1
      python -m venv venvs/gammacombo
      source venvs/gammacombo/bin/activate
      python -m pip install --upgrade pip
      python -m pip install -e . -e gammacombo
      cd gammacombo
  script:
    - bin/gammacharm_lhcb -c 605 --var g --ps 1 --scanrange 0.87:1.40
  artifacts:
    when: always
    paths:
      - gammacombo/plots/par
      - gammacombo/plots/scanner
    expire_in: 1 days
