repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: "\\.clang-format$"
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
-   repo: https://gitlab.cern.ch/lhcb-core/dev-tools/check-include-convention.git
    rev: 0.1.0
    hooks:
    -   id: check-include-convention
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
    -   id: clang-format
        exclude: 'core/include/tclap'
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: 'development'
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: 'quarterly'
