[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "gc_core"
version = "0.1.0"
description = "Plotting utils for the LHCb frequentist combination framework"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["core/src"]

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E7",
    "E9",
    "E101",
    "W1",
    "W6",
    # isort
    "I001"
]
ignore = [
    "E741", # Ambiguous variable name
]
