/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooHistPdfVar.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

RooHistPdfVar::RooHistPdfVar(const char *name, const char *title, 
    RooAbsReal& _xobs,
    RooAbsReal& _xth,
    RooAbsReal& _xshift) :
    RooAbsReal(name,title), 
    xobs("xobs","xobs",this,_xobs),
    xth("xth","xth",this,_xth),
    xshift("xshift","xshift",this,_xshift)
{ 
} 


RooHistPdfVar::RooHistPdfVar(const RooHistPdfVar& other, const char* name) :  
    RooAbsReal(other,name), 
    xobs("xobs",this,other.xobs),
    xth("xth",this,other.xth),
    xshift("xshift",this,other.xshift)
{ 
} 

RooHistPdfVar::~RooHistPdfVar() { }


Double_t RooHistPdfVar::evaluate() const 
{ 
    return double(xth) - double(xobs) + double(xshift);
    //return -double(xth) + double(xobs) + double(xshift);
} 

ClassImp(RooHistPdfVar)
