/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooPoly3Var.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

RooPoly3Var:: RooPoly3Var(const char *name, const char *title,
          RooAbsReal& _xobs,
          double& _p0,
          double& _p1,
          double& _p2,
          double& _p3) :
    RooAbsReal(name,title), 
    xobs("xobs","xobs",this,_xobs),
    p0(_p0),
    p1(_p1),
    p2(_p2),
    p3(_p3)
{ 
} 


RooPoly3Var::RooPoly3Var(const RooPoly3Var& other, const char* name) :  
    RooAbsReal(other,name), 
    xobs("xobs",this,other.xobs),
    p0(other.p0),
    p1(other.p1),
    p2(other.p2),
    p3(other.p3)
{ 
} 

RooPoly3Var::~RooPoly3Var() { }


Double_t RooPoly3Var::evaluate() const 
{ 
    double x = double(xobs);
    return p0 + p1*x + p2*x*x + p3*x*x*x;
} 

ClassImp(RooPoly3Var)
