/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOHISTPDFVAR
#define ROOHISTPDFVAR

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooHistPdfVar : public RooAbsReal {
public:
  RooHistPdfVar() {} ; 
  RooHistPdfVar(const char *name, const char *title,
	      RooAbsReal& _xobs,
	      RooAbsReal& _xth,
	      RooAbsReal& _xshift);
  RooHistPdfVar(const RooHistPdfVar& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooHistPdfVar(*this,newname); }
  virtual ~RooHistPdfVar();

protected:

  RooRealProxy xobs;
  RooRealProxy xth;
  RooRealProxy xshift;
  
  Double_t evaluate() const;

private:
  ClassDef(RooHistPdfVar, 1);
};
 
#endif
