/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOHISTPDFANGLEVAR
#define ROOHISTPDFANGLEVAR

#include <RooAbsReal.h>
#include <RooRealProxy.h>

class TObject;

class RooHistPdfAngleVar : public RooAbsReal {
 public:
  RooHistPdfAngleVar() {};
  RooHistPdfAngleVar(const char* name, const char* title, RooAbsReal& _xobs, RooAbsReal& _xth, RooAbsReal& _xshift);
  RooHistPdfAngleVar(const RooHistPdfAngleVar& other, const char* name = 0);
  virtual TObject* clone(const char* newname) const { return new RooHistPdfAngleVar(*this, newname); }
  virtual ~RooHistPdfAngleVar();

 protected:
  RooRealProxy xobs;
  RooRealProxy xth;
  RooRealProxy xshift;

  Double_t evaluate() const;

 private:
  ClassDef(RooHistPdfAngleVar, 1);
};

#endif
