/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPOLY3VAR
#define ROOPOLY3VAR

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPoly3Var : public RooAbsReal {
public:
  RooPoly3Var() {} ; 
  RooPoly3Var(const char *name, const char *title,
	      RooAbsReal& _xobs,
	      double& _p0,
	      double& _p1,
	      double& _p2,
	      double& _p3);
  RooPoly3Var(const RooPoly3Var& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPoly3Var(*this,newname); }
  virtual ~RooPoly3Var();

protected:

  RooRealProxy xobs;
  double p0;
  double p1;
  double p2;
  double p3;
  
  Double_t evaluate() const;

private:
  ClassDef(RooPoly3Var, 1);
};
 
#endif
