# Run GC CI tests

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches:
    - master
    - development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Get docker image
      run: docker pull gammacombo/gcimage

    - name: Make docker container
      run: |
        docker run --name gccont gammacombo/gcimage /bin/bash -c "sudo mkdir /code"
        docker cp . gccont:/code
        docker commit gccont gccontwfiles

    - name: Compile GC and save image
      run: |
        docker run --name gcbuild gccontwfiles /bin/bash -c "sudo mkdir /code/build; cd /code/build; sudo cmake ..; sudo make -j8 install"
        docker commit gcbuild gcbuiltimage

    - name: Run CI Tests
      run: docker run --name gcrun gcbuiltimage /bin/bash -c "cd /code; sudo python scripts/run_ci_tests.py"

    - name: Copy output
      run: docker cp gcrun:/code/tutorial/ci_logs .

    - name: Configure ssh keys
      if: github.actor == 'gammacombo'
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Publish output (if not a fork PR)
      if: github.actor == 'gammacombo'
      run: |
        git clone git@github.com:gammacombo/gammacombo.github.io.git
        cp ci_logs/* gammacombo.github.io/assets/images/ci/
        cd gammacombo.github.io
        git config --local user.email "gcci@cern.ch"
        git config --local user.name "gammacombo"
        touch ci.html
        git add ci.html
        git add assets/images/ci/*
        git commit -m "CI test results"
        git push origin master

    - name: Print Info
      if: github.actor == 'gammacombo'
      run: echo "Success. Check your CI tests at https://gammacombo.github.io/ci.html"

